name: LongerDays
version: 1.2
main: dk.muj.plugins.longerdays.LongerDays
description: A plugin that can make minecraft days longer.
website: http://muj.dk/plugins/longerdays
depend: [MassiveCore]
authors: [madus]

