# This will determine the length of the day. Values with comas are not supported.
# 2 = 40min, 3 = 60min, 4 = 80min, etc.
LengthMultiplier: 3
# How often the time should be set back, in ticks
#The higher the value the less server impact.
#The length multiplier should be divible with this number.
# 20 ticks = 1 second
Interval: 60


#In which world the days will be longer
worlds:
- world_1
- world_2
- world_3
